version: "3.6"
networks:
  localdev:
    name: localdev

services:    
  boilerplate-api:
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile
    image: boilerplate-api:local
    container_name: boilerplate-api
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - localdev