# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:    
  boilerplate-api:
    entrypoint: ["./wait-for.sh", "mssql:1433", "-t", "120", "--", "dotnet", "Boilerplate.Api.dll"]
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile
    image: boilerplate-api:local
    container_name: boilerplate-api
    networks:
      - localdev
    volumes:
      - ./etc/wait-for.sh:/app/wait-for.sh
